### ISSUE TITLE
Manual Assignment is Overridden

### ISSUE THREAD

**Issue by tdefreest** [berezuev/osticket-spreader#3]
When manually creating a ticket on behalf of the customer and selecting a specific individual for the ticket to be assigned to them, the spreader re-assigns the ticket to the next person in the queue instead of the specific individual I wanted.

Is there anyway to override the queue when you want a specific person assigned?  Right now, I have to go back into the ticket and reassign again, and now two people received notifications instead of the one.

Please see attached screen capture.

![capture](https://cloud.githubusercontent.com/assets/16881887/15509756/9ee16028-21a2-11e6-9dca-f6402d201b1a.PNG)

**Comment by Pietro-Aretino** [comment]
Pardon my ignorance, but should your files just be dumped into the /plugins directory for osTicket? What is the proper installation and running of your programs? Can I install them anywhere on the web-server and create a cronjob for it?

**Comment by berezuev** [comment]
@Pietro-Aretino you don't need to use crontab. This plugin installing in osticket admin pannel (/contact/scp), then it runs automatically on create ticket event.

**Comment by Pietro-Aretino** [comment]
Hey man,

Would you be willing to patch this for the latest version of osTicket?

It works perfectly when you create a ticket internally, but when you get an
email, the plugin breaks and the email never arrives and does not generate
an email.

This is the bounce-back error you get from the mail-server:

*Remote Server returned '554 5.3.0 < #5.3.0 x-unix; *

*PHP Fatal error: Call to a member function addNote() on null in
/var/www/osticket/upload/include/class.ticket.php on line 2635 PHP Stack
trace: *


*PHP 1. {main}() /var/www/osticket/upload/api/pipe.php:0 *

*PHP 2. PipeApiController::process()
/var/www/osticket/upload/api/pipe.php:26 *

*PHP 3. TicketApiController->processEmail()
/var/www/osticket/upload/include/api.tickets.php:222 *

*PHP 4. TicketApiController->createTicket()
/var/www/osticket/upload/include/api.tickets.php:178 *

*PHP 5. Ticket::create()
/var/www/osticket/upload/include/api.tickets.php:132 *

*PHP 6. Ticket->save()
/var/www/osticket/upload/include/class.ticket.php:3373 *

*PHP 7. VerySimpleModel->save()
/var/www/osticket/upload/include/class.ticket.php:2740 *

*PHP 8. Signal::send() /var/www/osticket/upload/include/class.orm.php:619 *

*PHP 9.
call_user_func_array:{/var/www/osticket/upload/include/class.signal.php:98}()
/var/www/osticket/upload/include/class.signal.php:98 *

*PHP 10. SpreaderPlugin::spreadTicket()
/var/www/osticket/upload/include/class.signal.php:98 *

*PHP 11. Ticket->assignToStaff()
/var/www/osticket/upload/include/plugins/osticket-spreader/spreader.php:56 *

*PHP 12. Ticket->onAssign()
/var/www/osticket/upload/include/class.ticket.php:2145 *

*PHP 13. Ticket->logNote()
/var/www/osticket/upload/include/class.ticket.php:1727 *

*PHP 14. Ticket->postNote()
/var/www/osticket/upload/include/class.ticket.php:2611>'*

**Comment by Nimeshin** [comment]
hi
great mod so far for this feature, however it breaks the email pull function as mentioned above. Any idea if this has been fixed or can be fixed? I managed to install on the latest 1.10 release.

**Comment by Nimeshin** [comment]
found your post now ( Pietro-Aretino ) to work in 1.10 - thank you all, works perfectly. 
http://osticket.com/forum/discussion/92292/auto-assign-tickets-based-on-time-of-day-cronjob 
Also, if you want this functioning and running on your osTicket 1.10.1, simply modify the code in spreader.php on line 25 from "model.created." to "ticket.created", and the auto-assignment should function just fine with no errors.

**Comment by berezuev** [comment]
Thanks @Pietro-Aretino and @Nimeshin.
I've done changes in this repo. Next time you're able to create PR with your fix. Anyway, thanks for your fix!
